//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string UnsignName { get; set; }
        public string SeoLink { get; set; }
        public string Address { get; set; }
        public string Province { get; set; }
        public string ProvinceSeolink { get; set; }
        public string District { get; set; }
        public string DistrictSeolink { get; set; }
        public byte Level { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public System.DateTime CreateTime { get; set; }
        public double Long { get; set; }
        public double Lang { get; set; }
        public string Introduce { get; set; }
        public int OrderNo { get; set; }
        public byte Status { get; set; }
        public int ViewNo { get; set; }
        public string Code { get; set; }
        public string Image { get; set; }
        public string Thumb { get; set; }
        public Nullable<int> LangId { get; set; }
    }
}
