//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateProduct
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string SeoLink { get; set; }
        public string EnglishName { get; set; }
        public short ParrentCateId { get; set; }
        public string ParrentCateName { get; set; }
        public short OrderNo { get; set; }
        public string Description { get; set; }
        public bool IsDelete { get; set; }
        public short ChildCount { get; set; }
        public Nullable<int> LangId { get; set; }
    }
}
