//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonInfo
    {
        public short ID { get; set; }
        public string HeadOffice { get; set; }
        public string HeadOffice_En { get; set; }
        public string Office { get; set; }
        public string Office_En { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string EnglishName { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Lang { get; set; }
        public string Facebook { get; set; }
        public string Yahoo { get; set; }
        public string Skype { get; set; }
        public string Logo { get; set; }
        public string Summary { get; set; }
        public string Summary_En { get; set; }
        public Nullable<byte> LangId { get; set; }
        public string Logo2 { get; set; }
        public Nullable<bool> IsShowService { get; set; }
        public Nullable<bool> IsShowProduct { get; set; }
        public Nullable<bool> IsShowSolution { get; set; }
    }
}
