//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigImage
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Name_En { get; set; }
        public string Image { get; set; }
        public string Url { get; set; }
        public Nullable<int> Status { get; set; }
        public string UnsignName { get; set; }
        public string UnsignName_En { get; set; }
        public Nullable<int> LangId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public string CreatedFullname { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
    }
}
