//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string UnsignName { get; set; }
        public string SeoLink { get; set; }
        public string EnglishName { get; set; }
        public string Summary { get; set; }
        public string Summary_En { get; set; }
        public string SeoLink_En { get; set; }
        public string Image { get; set; }
        public string SlideShow { get; set; }
        public string Content { get; set; }
        public string Content_En { get; set; }
        public short ViewNo { get; set; }
        public short OrderNo { get; set; }
        public short IsDelete { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<byte> LangId { get; set; }
    }
}
