//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string Image { get; set; }
        public string Website { get; set; }
        public string Image2 { get; set; }
        public short OrderNo { get; set; }
        public bool Status { get; set; }
        public Nullable<byte> LangId { get; set; }
    }
}
