//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSay
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public string Title_En { get; set; }
        public string Company { get; set; }
        public string Company_En { get; set; }
        public string Content { get; set; }
        public string Content_En { get; set; }
        public short OrderNo { get; set; }
        public string Image { get; set; }
        public Nullable<int> LangId { get; set; }
    }
}
