//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string SeoLink { get; set; }
        public string ProvinceSeoLink { get; set; }
        public string National { get; set; }
        public Nullable<byte> LangId { get; set; }
    }
}
