//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string SeoLink { get; set; }
        public string Title_En { get; set; }
        public string SeoLink_En { get; set; }
        public string Description { get; set; }
        public string Description_En { get; set; }
        public string Requirement { get; set; }
        public string Requirement_En { get; set; }
        public string Benefit { get; set; }
        public string Benefit_En { get; set; }
        public string Address { get; set; }
        public string Number { get; set; }
        public string Profile { get; set; }
        public string ContactInfo { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<byte> LangId { get; set; }
    }
}
