//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public int CateId { get; set; }
        public string Title { get; set; }
        public string SeoLink { get; set; }
        public string Title_En { get; set; }
        public string SeoLink_En { get; set; }
        public string Image { get; set; }
        public string Summary { get; set; }
        public string Summary_En { get; set; }
        public string Content { get; set; }
        public string Content_En { get; set; }
        public System.DateTime PostTime { get; set; }
        public string Author { get; set; }
        public int ViewNo { get; set; }
        public short IsHot { get; set; }
        public byte Status { get; set; }
        public string UnsignTitle { get; set; }
        public Nullable<int> LangId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public string CreatedFullname { get; set; }
    }
}
