//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public int CateId { get; set; }
        public string CreateDate { get; set; }
        public string Customer { get; set; }
        public string Name { get; set; }
        public string SeoLink { get; set; }
        public string UnsignName { get; set; }
        public string EnglishName { get; set; }
        public string SeoLink_En { get; set; }
        public string Image { get; set; }
        public string Summary { get; set; }
        public string Summary_En { get; set; }
        public string Content { get; set; }
        public string Content_En { get; set; }
        public int ViewNo { get; set; }
        public Nullable<short> OrderNo { get; set; }
        public byte Status { get; set; }
        public bool IsDelete { get; set; }
        public string Tags { get; set; }
        public byte IsHot { get; set; }
        public Nullable<int> LangId { get; set; }
    }
}
