//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracker
    {
        public long ID { get; set; }
        public string Browser { get; set; }
        public string Version { get; set; }
        public string OS { get; set; }
        public string PageUrl { get; set; }
        public string UrlReferrer { get; set; }
        public string SessionID { get; set; }
        public string IP { get; set; }
        public System.DateTime InTime { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public bool IsMobileDevice { get; set; }
        public string MobileDeviceManufacturer { get; set; }
        public Nullable<int> LangId { get; set; }
    }
}
