var styleSwitcher = {
    initialized: !1, options: { color: "#CCC", gradient: "false" }, initialize: function () {
        var a = this; this.initialized || (jQuery.styleSwitcherCachedScript = function (a, b) { return b = $.extend(b || {}, { dataType: "script", cache: !0, url: a }), jQuery.ajax(b) }, $("head").append($('<link rel="stylesheet">').attr("href", "/content/v.1/css/style-switcher.css")), $("head").append($('<link rel="stylesheet/less">').attr("href", "master/less/skin.less")),
            $("head").append($('<link rel="stylesheet">').attr("href", "/content/v.1/css/colorpicker.css")), $.styleSwitcherCachedScript("/scripts/v.1/colorpicker.js").done(function () { less = { env: "development" }, $.styleSwitcherCachedScript("/scripts/v.1/less.js").done(function () { a.build(), a.events(), null != $.cookie("colorGradient") && (a.options.gradient = $.cookie("colorGradient")), null != $.cookie("skin") ? a.setColor($.cookie("skin")) : a.container.find("ul[data-type=colors] li:first a").click(), null != $.cookie("layout") && a.setLayoutStyle($.cookie("layout")), null != $.cookie("backgroundcolor") && a.setBackgroundColor($.cookie("backgroundcolor")), null != $.cookie("pattern") && a.setPattern($.cookie("pattern")), null == $.cookie("initialized") && (a.container.find("h4 a").click(), $.cookie("initialized", !0)), a.initialized = !0 }) }),
        $.styleSwitcherCachedScript("/scripts/v.1/cssbeautify.js").done(function () { }))
    }, build: function () {
        
    }, events: function () { var a = this; a.container.find("h4 a").click(function (b) { b.preventDefault(), a.container.hasClass("active") ? a.container.animate({ left: "-" + a.container.width() + "px" }, 300).removeClass("active") : a.container.animate({ left: "0" }, 300).addClass("active") }), (null != $.cookie("showSwitcher") || $("body").hasClass("one-page")) && (a.container.find("h4 a").click(), $.removeCookie("showSwitcher")) }, setColor: function (a) { var b = this; return this.isChanging ? !1 : (b.options.color = a, less.modifyVars({ gradient: b.options.gradient, skinColor: a }), $.cookie("skin", a), void this.setLogo()) }, setLayoutStyle: function (a, b) {
        if ($("body").hasClass("one-page")) return !1; if ($.cookie("layout", a), b) return $.cookie("showSwitcher", !0), window.location.reload(), !1; var c = this.container.find("div.options-links.layout"),
            d = this.container.find("div.patterns"); c.find("a.active").removeClass("active"), c.find("a[data-layout-type=" + a + "]").addClass("active"), "wide" == a ? (d.hide(), $("body").removeClass("boxed"), $.removeCookie("pattern")) : (d.show(), $("body").addClass("boxed"), null == $.cookie("pattern") && this.container.find("ul[data-type=patterns] li:first a").click())
    }, setBackgroundColor: function (a) { $.cookie("backgroundcolor", a); var b = this.container.find("div.options-links.background-color"); b.find("a.active").removeClass("active"), b.find("a[data-background-color=" + a + "]").addClass("active"), "dark" == a ? $("body").addClass("dark") : $("body").removeClass("dark"), this.setLogo() }, setPattern: function (a) { var b = $("body").hasClass("boxed"); b && $("body").css("background-image", "url(img/patterns/" + a + ".png)"), $.cookie("pattern", a) }, setLogo: function () { $.cookie("skin") == this.container.find("ul[data-type=colors] li:first a").attr("data-color-hex") && "dark" != $.cookie("backgroundcolor") ? $("h1.logo img").attr("src", "img/logo-default.png") : "dark" == $.cookie("backgroundcolor") ? $("h1.logo img").attr("src", "img/logo-dark.png") : $("h1.logo img").attr("src", "img/logo.png") }, reset: function () { $.removeCookie("skin"), $.removeCookie("layout"), $.removeCookie("backgroundcolor"), $.removeCookie("pattern"), $.removeCookie("colorGradient"), $.cookie("showSwitcher", !0), window.location.reload() }, getCss: function () { raw = ""; var a = $("body").hasClass("boxed"); a ? (raw = 'body { background-image: url("img/patterns/' + $.cookie("pattern") + '.png"); }', $("#addBoxedClassInfo").show()) : $("#addBoxedClassInfo").hide(), $("#getCSSTextarea").text(""), $("#getCSSTextarea").text($('style[id^="less:"]').text()), $("#getCSSModal").modal("show"), options = { indent: "	", autosemicolon: !0 }, raw += $("#getCSSTextarea").text(), $("#getCSSTextarea").text(cssbeautify(raw, options)) }
}; styleSwitcher.initialize();