//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ATIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ATIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATI.Web.Resource.ATIResource", typeof(ATIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký làm đại lý.
        /// </summary>
        public static string BranchRegister {
            get {
                return ResourceManager.GetString("BranchRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi!.
        /// </summary>
        public static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua sản phẩm.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tin tức khác.
        /// </summary>
        public static string CateNewsOther_Label {
            get {
                return ResourceManager.GetString("CateNewsOther_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm sản phẩm.
        /// </summary>
        public static string CateProduct_Label {
            get {
                return ResourceManager.GetString("CateProduct_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm giải pháp khác.
        /// </summary>
        public static string CateSolutionsOther_Label {
            get {
                return ResourceManager.GetString("CateSolutionsOther_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khiếu nại.
        /// </summary>
        public static string ClaimContact {
            get {
                return ResourceManager.GetString("ClaimContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp tác.
        /// </summary>
        public static string CombineContact {
            get {
                return ResourceManager.GetString("CombineContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu bạn quan tâm đến các sản phẩm, dịch vụ của chúng tôi, hãy điền email liên hệ ngay với chúng tôi....
        /// </summary>
        public static string CommentContact {
            get {
                return ResourceManager.GetString("CommentContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        public static string CompanyCategory {
            get {
                return ResourceManager.GetString("CompanyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Với chiến lược kinh doanh vì  lợi ích công cộng, chúng tôi hiểu việc không ngừng nghiên cứu và cải tiến công nghệ sẽ là chìa khóa quan trọng nhất trong tiến trình phát triển bền vững.
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án tiêu biểu.
        /// </summary>
        public static string ConstructionCode {
            get {
                return ResourceManager.GetString("ConstructionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string ContactAdd {
            get {
                return ResourceManager.GetString("ContactAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string ContactCode {
            get {
                return ResourceManager.GetString("ContactCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string ContactCompany {
            get {
                return ResourceManager.GetString("ContactCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string ContactContent {
            get {
                return ResourceManager.GetString("ContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string ContactInfo_Label {
            get {
                return ResourceManager.GetString("ContactInfo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Cảm ơn bạn đã quan tâm đến sản phẩm, dịch vụ của chúng tôi. Để liên hệ sử dụng dịch vụ, hợp tác bạn hãy điền thông tin vào mẫu biểu dưới đây. Chúng tôi sẽ liên hệ lại với bạn ngay sau khi nhận được thông tin liên hệ.&lt;/p&gt;&lt;br&gt;.
        /// </summary>
        public static string ContactThank {
            get {
                return ResourceManager.GetString("ContactThank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        public static string ContactUs_Label {
            get {
                return ResourceManager.GetString("ContactUs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả sản phẩm.
        /// </summary>
        public static string Description_Product {
            get {
                return ResourceManager.GetString("Description_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi! Không thể tìm thấy trang!.
        /// </summary>
        public static string Error_404 {
            get {
                return ResourceManager.GetString("Error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string EventCategory {
            get {
                return ResourceManager.GetString("EventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form liên hệ.
        /// </summary>
        public static string FormContact {
            get {
                return ResourceManager.GetString("FormContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string HomeCode {
            get {
                return ResourceManager.GetString("HomeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con người.
        /// </summary>
        public static string HumanCategory {
            get {
                return ResourceManager.GetString("HumanCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /gioi-thieu/ve-cong-ty.
        /// </summary>
        public static string ICompanyCode {
            get {
                return ResourceManager.GetString("ICompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /gioi-thieu/con-nguoi.
        /// </summary>
        public static string IHumanCode {
            get {
                return ResourceManager.GetString("IHumanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string ImageCode {
            get {
                return ResourceManager.GetString("ImageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        public static string IntroductionCode {
            get {
                return ResourceManager.GetString("IntroductionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi nỗ lực làm thay đổi cuộc sống tốt đẹp hơn thông qua các sản phẩm và dịch vụ và&lt;br&gt; sự nỗ lực làm việc tận tâm vì khách hàng.
        /// </summary>
        public static string LineOneBanner {
            get {
                return ResourceManager.GetString("LineOneBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tin-su-kien.
        /// </summary>
        public static string LinkEvent {
            get {
                return ResourceManager.GetString("LinkEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tin-moi.
        /// </summary>
        public static string LinkNew {
            get {
                return ResourceManager.GetString("LinkNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách liên hệ.
        /// </summary>
        public static string ListContact {
            get {
                return ResourceManager.GetString("ListContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di động.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết khác.
        /// </summary>
        public static string MorePosts_Label {
            get {
                return ResourceManager.GetString("MorePosts_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công Ty Cổ Phần ĐầuTư Xây Dựng &amp; &lt;/br&gt;Tư Vấn FCN Build.
        /// </summary>
        public static string NameCompany {
            get {
                return ResourceManager.GetString("NameCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới.
        /// </summary>
        public static string NewCode {
            get {
                return ResourceManager.GetString("NewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        public static string NewPaper {
            get {
                return ResourceManager.GetString("NewPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận tin mới.
        /// </summary>
        public static string NewReceive {
            get {
                return ResourceManager.GetString("NewReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức mới nhất.
        /// </summary>
        public static string NewsLastest_Label {
            get {
                return ResourceManager.GetString("NewsLastest_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        public static string PartnerCode {
            get {
                return ResourceManager.GetString("PartnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng bởi.
        /// </summary>
        public static string PostedBy_Label {
            get {
                return ResourceManager.GetString("PostedBy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỏi, đáp.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận thư mới.
        /// </summary>
        public static string ReceiveInbox {
            get {
                return ResourceManager.GetString("ReceiveInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển dụng.
        /// </summary>
        public static string RecruitmentCode {
            get {
                return ResourceManager.GetString("RecruitmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm liên quan.
        /// </summary>
        public static string RelatedProducts_Label {
            get {
                return ResourceManager.GetString("RelatedProducts_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhu cầu.
        /// </summary>
        public static string Requirement {
            get {
                return ResourceManager.GetString("Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiềm sản phẩm.
        /// </summary>
        public static string Search_Label {
            get {
                return ResourceManager.GetString("Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm.
        /// </summary>
        public static string SearchResults_Label {
            get {
                return ResourceManager.GetString("SearchResults_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đi.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thành công!.
        /// </summary>
        public static string Sendmail {
            get {
                return ResourceManager.GetString("Sendmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi tin nhắn.
        /// </summary>
        public static string SendMessage_Label {
            get {
                return ResourceManager.GetString("SendMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        public static string ServiceCode {
            get {
                return ResourceManager.GetString("ServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ khác biệt.
        /// </summary>
        public static string ServiceSpecial {
            get {
                return ResourceManager.GetString("ServiceSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        public static string ShowHomePage_Label {
            get {
                return ResourceManager.GetString("ShowHomePage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mạng xã hội.
        /// </summary>
        public static string SocialNetwork_Label {
            get {
                return ResourceManager.GetString("SocialNetwork_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;caption-text&quot;&gt;&lt;i class=&quot;icon icon-chevron-circle-right&quot;&gt;&lt;/i&gt; Chúng tôi cung cấp giải pháp tổng thể&lt;/div&gt;
        ///                    &lt;div class=&quot;caption-text&quot; &gt;&lt;i class=&quot;icon icon-chevron-circle-right&quot;&gt;&lt;/i&gt; Đem lại lợi ích cho khách hàng&lt;/div&gt;
        ///                    &lt;div class=&quot;caption-text&quot; &gt;&lt;i class=&quot;icon icon-chevron-circle-right&quot;&gt;&lt;/i&gt; Bằng sự khác biệt về công nghệ&lt;/div&gt;
        ///                    &lt;div class=&quot;caption-text&quot; &gt;&lt;i class=&quot;icon icon-chevron-circle-right&quot;&gt;&lt;/i&gt; Luôn luôn đúng tiến độ với&lt;/div&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sologan {
            get {
                return ResourceManager.GetString("Sologan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;caption-text&quot;&gt;&quot;Sáng tạo, tối ưu từng chi tiết, từng nguồn lực,&lt;br /&gt;dịch vụ chuyên nghiệp giúp chúng tôi khác biệt&quot;&lt;/div&gt;.
        /// </summary>
        public static string Sologan1 {
            get {
                return ResourceManager.GetString("Sologan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải pháp.
        /// </summary>
        public static string Solutions_Label {
            get {
                return ResourceManager.GetString("Solutions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian gửi.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại liên hệ.
        /// </summary>
        public static string TypeContact {
            get {
                return ResourceManager.GetString("TypeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 class=&quot;short word-rotator-title&quot;&gt;
        ///                Giá trị cốt lõi của chúng tôi
        ///                &lt;strong class=&quot;inverted&quot;&gt;
        ///                    &lt;span style=&quot;height: 54px;&quot; class=&quot;word-rotate active&quot;&gt;
        ///                        &lt;span style=&quot;top: -107.347px;&quot; class=&quot;word-rotate-items&quot;&gt;
        ///                            &lt;span&gt;Làm việc Hiệu quả&lt;/span&gt;
        ///                            &lt;span&gt;Làm việc Chủ động&lt;/span&gt;
        ///                            &lt;span&gt;Làm việc có Hệ thống&lt;/span&gt;
        ///                            &lt;span&gt;Làm vi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ValueCode {
            get {
                return ResourceManager.GetString("ValueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        public static string ViewAll_Label {
            get {
                return ResourceManager.GetString("ViewAll_Label", resourceCulture);
            }
        }
    }
}
