//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATI.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ATIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ATIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATI.Web.Resource.ATIResource", typeof(ATIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký làm đại lý.
        /// </summary>
        internal static string BranchRegister {
            get {
                return ResourceManager.GetString("BranchRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi!.
        /// </summary>
        internal static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua sản phẩm.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tin tức khác.
        /// </summary>
        internal static string CateNewsOther_Label {
            get {
                return ResourceManager.GetString("CateNewsOther_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm sản phẩm.
        /// </summary>
        internal static string CateProduct_Label {
            get {
                return ResourceManager.GetString("CateProduct_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm giải pháp khác.
        /// </summary>
        internal static string CateSolutionsOther_Label {
            get {
                return ResourceManager.GetString("CateSolutionsOther_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khiếu nại.
        /// </summary>
        internal static string ClaimContact {
            get {
                return ResourceManager.GetString("ClaimContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp tác.
        /// </summary>
        internal static string CombineContact {
            get {
                return ResourceManager.GetString("CombineContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu bạn quan tâm đến các sản phẩm, dịch vụ của chúng tôi, hãy điền email liên hệ ngay với chúng tôi....
        /// </summary>
        internal static string CommentContact {
            get {
                return ResourceManager.GetString("CommentContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string CompanyCategory {
            get {
                return ResourceManager.GetString("CompanyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Với chiến lược kinh doanh vì  lợi ích công cộng, chúng tôi hiểu việc không ngừng nghiên cứu và cải tiến công nghệ sẽ là chìa khóa quan trọng nhất trong tiến trình phát triển bền vững.
        /// </summary>
        internal static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án tiêu biểu.
        /// </summary>
        internal static string ConstructionCode {
            get {
                return ResourceManager.GetString("ConstructionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string ContactAdd {
            get {
                return ResourceManager.GetString("ContactAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string ContactCode {
            get {
                return ResourceManager.GetString("ContactCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        internal static string ContactCompany {
            get {
                return ResourceManager.GetString("ContactCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string ContactContent {
            get {
                return ResourceManager.GetString("ContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        internal static string ContactInfo_Label {
            get {
                return ResourceManager.GetString("ContactInfo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Cảm ơn bạn đã quan tâm đến sản phẩm, dịch vụ của chúng tôi. Để liên hệ sử dụng dịch vụ, hợp tác bạn hãy điền thông tin vào mẫu biểu dưới đây. Chúng tôi sẽ liên hệ lại với bạn ngay sau khi nhận được thông tin liên hệ.&lt;/p&gt;&lt;br&gt;.
        /// </summary>
        internal static string ContactThank {
            get {
                return ResourceManager.GetString("ContactThank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        internal static string ContactUs_Label {
            get {
                return ResourceManager.GetString("ContactUs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả sản phẩm.
        /// </summary>
        internal static string Description_Product {
            get {
                return ResourceManager.GetString("Description_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        internal static string EventCategory {
            get {
                return ResourceManager.GetString("EventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form liên hệ.
        /// </summary>
        internal static string FormContact {
            get {
                return ResourceManager.GetString("FormContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string HomeCode {
            get {
                return ResourceManager.GetString("HomeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con người.
        /// </summary>
        internal static string HumanCategory {
            get {
                return ResourceManager.GetString("HumanCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /gioi-thieu/ve-cong-ty.
        /// </summary>
        internal static string ICompanyCode {
            get {
                return ResourceManager.GetString("ICompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /gioi-thieu/con-nguoi.
        /// </summary>
        internal static string IHumanCode {
            get {
                return ResourceManager.GetString("IHumanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string ImageCode {
            get {
                return ResourceManager.GetString("ImageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string IntroductionCode {
            get {
                return ResourceManager.GetString("IntroductionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi nỗ lực làm thay đổi cuộc sống tốt đẹp hơn thông qua các sản phẩm và dịch vụ và&lt;br&gt; sự nỗ lực làm việc tận tâm vì khách hàng.
        /// </summary>
        internal static string LineOneBanner {
            get {
                return ResourceManager.GetString("LineOneBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tin-su-kien.
        /// </summary>
        internal static string LinkEvent {
            get {
                return ResourceManager.GetString("LinkEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tin-moi.
        /// </summary>
        internal static string LinkNew {
            get {
                return ResourceManager.GetString("LinkNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách liên hệ.
        /// </summary>
        internal static string ListContact {
            get {
                return ResourceManager.GetString("ListContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di động.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết khác.
        /// </summary>
        internal static string MorePosts_Label {
            get {
                return ResourceManager.GetString("MorePosts_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công Ty Cổ Phần ĐầuTư Xây Dựng &amp; &lt;/br&gt;Tư Vấn FCN Build.
        /// </summary>
        internal static string NameCompany {
            get {
                return ResourceManager.GetString("NameCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới.
        /// </summary>
        internal static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới.
        /// </summary>
        internal static string NewCode {
            get {
                return ResourceManager.GetString("NewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        internal static string NewPaper {
            get {
                return ResourceManager.GetString("NewPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận tin mới.
        /// </summary>
        internal static string NewReceive {
            get {
                return ResourceManager.GetString("NewReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức mới nhất.
        /// </summary>
        internal static string NewsLastest_Label {
            get {
                return ResourceManager.GetString("NewsLastest_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        internal static string PartnerCode {
            get {
                return ResourceManager.GetString("PartnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng bởi.
        /// </summary>
        internal static string PostedBy_Label {
            get {
                return ResourceManager.GetString("PostedBy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỏi, đáp.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận thư mới.
        /// </summary>
        internal static string ReceiveInbox {
            get {
                return ResourceManager.GetString("ReceiveInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển dụng.
        /// </summary>
        internal static string RecruitmentCode {
            get {
                return ResourceManager.GetString("RecruitmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm liên quan.
        /// </summary>
        internal static string RelatedProducts_Label {
            get {
                return ResourceManager.GetString("RelatedProducts_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhu cầu.
        /// </summary>
        internal static string Requirement {
            get {
                return ResourceManager.GetString("Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiềm.
        /// </summary>
        internal static string Search_Label {
            get {
                return ResourceManager.GetString("Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đi.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thành công!.
        /// </summary>
        internal static string Sendmail {
            get {
                return ResourceManager.GetString("Sendmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi tin nhắn.
        /// </summary>
        internal static string SendMessage_Label {
            get {
                return ResourceManager.GetString("SendMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        internal static string ServiceCode {
            get {
                return ResourceManager.GetString("ServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ khác biệt.
        /// </summary>
        internal static string ServiceSpecial {
            get {
                return ResourceManager.GetString("ServiceSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        internal static string ShowHomePage_Label {
            get {
                return ResourceManager.GetString("ShowHomePage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mạng xã hội.
        /// </summary>
        internal static string SocialNetwork_Label {
            get {
                return ResourceManager.GetString("SocialNetwork_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;caption-text&quot;&gt;&lt;i class=&quot;icon icon-chevron-circle-right&quot;&gt;&lt;/i&gt; Chúng tôi cung cấp giải pháp tổng thể&lt;/div&gt;
        ///                    &lt;div class=&quot;caption-text&quot; &gt;&lt;i class=&quot;icon icon-chevron-circle-right&quot;&gt;&lt;/i&gt; Đem lại lợi ích cho khách hàng&lt;/div&gt;
        ///                    &lt;div class=&quot;caption-text&quot; &gt;&lt;i class=&quot;icon icon-chevron-circle-right&quot;&gt;&lt;/i&gt; Bằng sự khác biệt về công nghệ&lt;/div&gt;
        ///                    &lt;div class=&quot;caption-text&quot; &gt;&lt;i class=&quot;icon icon-chevron-circle-right&quot;&gt;&lt;/i&gt; Luôn luôn đúng tiến độ với&lt;/div&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sologan {
            get {
                return ResourceManager.GetString("Sologan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;caption-text&quot;&gt;&quot;Sáng tạo, tối ưu từng chi tiết, từng nguồn lực,&lt;br /&gt;dịch vụ chuyên nghiệp giúp chúng tôi khác biệt&quot;&lt;/div&gt;.
        /// </summary>
        internal static string Sologan1 {
            get {
                return ResourceManager.GetString("Sologan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải pháp.
        /// </summary>
        internal static string Solutions_Label {
            get {
                return ResourceManager.GetString("Solutions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian gửi.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại liên hệ.
        /// </summary>
        internal static string TypeContact {
            get {
                return ResourceManager.GetString("TypeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 class=&quot;short word-rotator-title&quot;&gt;
        ///                Giá trị cốt lõi của chúng tôi
        ///                &lt;strong class=&quot;inverted&quot;&gt;
        ///                    &lt;span style=&quot;height: 54px;&quot; class=&quot;word-rotate active&quot;&gt;
        ///                        &lt;span style=&quot;top: -107.347px;&quot; class=&quot;word-rotate-items&quot;&gt;
        ///                            &lt;span&gt;Làm việc Hiệu quả&lt;/span&gt;
        ///                            &lt;span&gt;Làm việc Chủ động&lt;/span&gt;
        ///                            &lt;span&gt;Làm việc có Hệ thống&lt;/span&gt;
        ///                            &lt;span&gt;Làm vi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValueCode {
            get {
                return ResourceManager.GetString("ValueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        internal static string ViewAll_Label {
            get {
                return ResourceManager.GetString("ViewAll_Label", resourceCulture);
            }
        }
    }
}
